### PR TITLE
[fix] [txn] Get previous position by managed ledger.

### PR DESCRIPTION
**Pull request by thetumbled**
### Motivation

Max read position is before the first ongoing txn's position. But the entry id of the first message may be 0, calculate the max read position by `entry id - 1` is unsafe.

### Modifications

Calculate the max read position by method `managedLedger.getPreviousPosition`.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/thetumbled/pulsar/pull/42

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java [hunk 1]
```diff
@@ -287,8 +287,8 @@ private void handleTransactionMessage(TxnID txnId, Position position) {
                 .checkAbortedTransaction(txnId)) {
             ongoingTxns.put(txnId, (PositionImpl) position);
             PositionImpl firstPosition = ongoingTxns.get(ongoingTxns.firstKey());
-            //max read position is less than first ongoing transaction message position, so entryId -1
-            maxReadPosition = PositionImpl.get(firstPosition.getLedgerId(), firstPosition.getEntryId() - 1);
+            // max read position is less than first ongoing transaction message position, so entryId -1
```
Comment (liangyepianzhou) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java:290]: Please modify the notes here.

Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java]: done.

**Review by congbobo184 — COMMENTED** [review]
please add a test for this change

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java [hunk 2]
```diff
@@ -442,14 +442,22 @@ private void takeSnapshotByTimeout() {
                 takeSnapshotIntervalTime, TimeUnit.MILLISECONDS);
     }
 
+    private PositionImpl getPreviousPosition(PositionImpl position) {
+        return ((ManagedLedgerImpl) topic.getManagedLedger()).getPreviousPosition(position);
+    }
+
+    private PositionImpl getLastConfirmedEntry() {
```
Comment (dao-jun) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java:449]: seems we don't need the method.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java [hunk 3]
```diff
@@ -287,8 +287,8 @@ private void handleTransactionMessage(TxnID txnId, Position position) {
                 .checkAbortedTransaction(txnId)) {
             ongoingTxns.put(txnId, (PositionImpl) position);
             PositionImpl firstPosition = ongoingTxns.get(ongoingTxns.firstKey());
-            //max read position is less than first ongoing transaction message position, so entryId -1
-            maxReadPosition = PositionImpl.get(firstPosition.getLedgerId(), firstPosition.getEntryId() - 1);
+            // max read position is less than first ongoing transaction message position
+            maxReadPosition = getPreviousPosition(firstPosition);
```
Comment (dao-jun) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java:291]: In fact, `entryId=-1` does not cause program exceptions, There are many uses of this in pulsar. But if modified here, it is also acceptable

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java [hunk 4]
```diff
@@ -442,14 +442,22 @@ private void takeSnapshotByTimeout() {
                 takeSnapshotIntervalTime, TimeUnit.MILLISECONDS);
     }
 
+    private PositionImpl getPreviousPosition(PositionImpl position) {
```
Comment (dao-jun) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java:445]: remove the method and use ` topic.getManagedLedger()).getPreviousPosition(position);` directly is enough.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java (hunk 3 above)
Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java:291]: There are two places that we need to get the previous position, but they are not consistent. We have better make them consistent.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java (hunk 2 above)
Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java]: fixed.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java (hunk 4 above)
Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java]: fixed.

**Comment by thetumbled** [comment]
PTAL, thanks. @dao-jun @congbobo184 @liangyepianzhou

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java (hunk 3 above)
Comment (dao-jun) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java]: it makes sense

**Review by dao-jun — APPROVED** [review]

**Review by liangyepianzhou — CHANGES_REQUESTED** [review]
Good catch. Please help supplement the testing.

**Comment by thetumbled** [comment]
Hi, I have add a test to produce a exception, and it is necessary to fix this problem.
PTAL, thanks. @dao-jun @congbobo184 @liangyepianzhou

**Review by liangyepianzhou — APPROVED** [review]

**Comment by Technoboy-** [comment]
@dao-jun It's better to check which branches we need to release before merging. 
@liangyepianzhou please help label the branches

**Comment by heesung-sn** [comment]
This fails the build in branch-3.0 now. Please help to fix this issue.

@Technoboy- @thetumbled  

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project pulsar-broker: Compilation failure
[ERROR] /Users/hsohn/Workspace/pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java:[286,33] cannot find symbol
[ERROR]   symbol:   class ManagedLedgerImpl
[ERROR]   location: class org.apache.pulsar.broker.transaction.buffer.impl.TopicTransactionBuffer
```

**Comment by lhotari** [comment]
> This fails the build in branch-3.0 now. Please help to fix this issue.
> 
> @Technoboy- @thetumbled
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project pulsar-broker: Compilation failure
> [ERROR] /Users/hsohn/Workspace/pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java:[286,33] cannot find symbol
> [ERROR]   symbol:   class ManagedLedgerImpl
> [ERROR]   location: class org.apache.pulsar.broker.transaction.buffer.impl.TopicTransactionBuffer
> ```

@Technoboy- can this be reverted from branch-3.0 ?

**Comment by thetumbled** [comment]
> > This fails the build in branch-3.0 now. Please help to fix this issue.
> > @Technoboy- @thetumbled
> > ```
> > [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project pulsar-broker: Compilation failure
> > [ERROR] /Users/hsohn/Workspace/pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java:[286,33] cannot find symbol
> > [ERROR]   symbol:   class ManagedLedgerImpl
> > [ERROR]   location: class org.apache.pulsar.broker.transaction.buffer.impl.TopicTransactionBuffer
> > ```
> 
> @Technoboy- can this be reverted from branch-3.0 ?

It seems that the problem has been fixed by @Technoboy.

**Comment by lhotari** [comment]
> It seems that the problem has been fixed by @Technoboy.
@thetumbled How was it fixed? we need the fix to branch-3.0 .

**Comment by thetumbled** [comment]
> > It seems that the problem has been fixed by @Technoboy.
> 
> @thetumbled How was it fixed? we need the fix to branch-3.0 .

commit: 55788734a53acd505d97e6f8b3b4bd567603d9ce
image

**Comment by thetumbled** [comment]
> @thetumbled Thanks. There's a test failure in branch-3.0 too, to reproduce:
> 
> ```
> mvn -Pcore-modules,-main -T 1C clean -DskipTests -Dspotbugs.skip=true
> mvn -DredirectTestOutputToFile=false -DtestRetryCount=0 test -pl pulsar-broker -Dtest=TopicTransactionBufferTest
> ```

Let me take a look at this issue.

**Comment by Technoboy-** [comment]
```
TopicTransactionBufferTest.testGetLastMessageIdsWithOngoingTransactions
```
Revert this pr and the test still failed

**Comment by thetumbled** [comment]
> @thetumbled Thanks. There's a test failure in branch-3.0 too, to reproduce:
> 
> ```
> mvn -Pcore-modules,-main -T 1C clean -DskipTests -Dspotbugs.skip=true
> mvn -DredirectTestOutputToFile=false -DtestRetryCount=0 test -pl pulsar-broker -Dtest=TopicTransactionBufferTest
> ```

The problem is fixed by pr: https://github.com/apache/pulsar/pull/22130
