### PR TITLE
[fix][broker] upgrade jclouds 2.5.0 -> 2.6.0

### LINKED ISSUE #15159: Offloading large ledgers (>2GB) fail with Google Cloud Storage
**Describe the bug**

Offloading large ledgers fail with Google Cloud Storage and the default settings. With default settings offloading ledgers over 2GB will fail to GCS since there's a limitation in JClouds (reported as [[JCLOUDS-1606] Cannot upload more than 32 parts to GCS](https://issues.apache.org/jira/browse/JCLOUDS-1606)) which limits a multipart upload to 32 parts. GCS supports multipart uploads up to 10000 parts, but JClouds doesn't use the API in a way to achieve more than 32 parts.

Here's an example log entry of the problem:
```
java.util.concurrent.CompletionException: org.jclouds.http.HttpResponseException: command: POST https://www.googleapis.com/storage/v1/b/somebucket/o/ff553922-1fa3-4ceb-abcd-60106603b5c8-object-123456/compose HTTP/1.1 failed with response: HTTP/1.1 400 Bad Request; content: [{
  "error": {
    "code": 400,
    "message": "The number of source components provided (35) exceeds the maximum (32)",
    "errors": [
      {
        "message": "The number of source components provided (35) exceeds the maximum (32)",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
]
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
        at org.apache.bookkeeper.mledger.offload.jcloud.impl.BlobStoreManagedLedgerOffloader.lambda$offload$0(BlobStoreManagedLedgerOffloader.java:237) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131) [com.google.guava-guava-31.0.1-jre.jar:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
        at org.apache.bookkeeper.mledger.offload.jcloud.impl.BlobStoreManagedLedgerOffloader.lambda$offload$0(BlobStoreManagedLedgerOffloader.java:237) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131) [com.google.guava-guava-31.0.1-jre.jar:?]
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74) [com.google.guava-guava-31.0.1-jre.jar:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82) [com.google.guava-guava-31.0.1-jre.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.jclouds.http.HttpResponseException: command: POST https://www.googleapis.com/storage/v1/b/somebucket/o/ff553922-1fa3-4ceb-abcd-60106603b5c8-object-123456/compose HTTP/1.1 failed with response: HTTP/1.1 400 Bad Request; content: [{
  "error": {
    "code": 400,
    "message": "The number of source components provided (35) exceeds the maximum (32)",
    "errors": [
      {
        "message": "The number of source components provided (35) exceeds the maximum (32)",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
]
        at org.jclouds.googlecloudstorage.handlers.GoogleCloudStorageErrorHandler.handleError(GoogleCloudStorageErrorHandler.java:40) ~[?:?]
        at org.jclouds.http.handlers.DelegatingErrorHandler.handleError(DelegatingErrorHandler.java:65) ~[?:?]
        at org.jclouds.http.internal.BaseHttpCommandExecutorService.shouldContinue(BaseHttpCommandExecutorService.java:138) ~[?:?]
        at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:107) ~[?:?]
        at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91) ~[?:?]
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74) ~[?:?]
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45) ~[?:?]
        at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117) ~[?:?]
        at org.apache.pulsar.jcloud.shade.com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[?:?]
        at com.sun.proxy.$Proxy144.composeObjects(Unknown Source) ~[?:?]
        at org.jclouds.googlecloudstorage.blobstore.GoogleCloudStorageBlobStore.completeMultipartUpload(GoogleCloudStorageBlobStore.java:405) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor373.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.pulsar.jcloud.shade.com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50) ~[?:?]
        at com.sun.proxy.$Proxy88.completeMultipartUpload(Unknown Source) ~[?:?]
        at org.apache.bookkeeper.mledger.offload.jcloud.impl.BlobStoreManagedLedgerOffloader.lambda$offload$0(BlobStoreManagedLedgerOffloader.java:226) ~[?:?]
        ... 11 more
```

**To Reproduce**
1. Configure offloading to use GCS
2. Produce a lot of messages
3. Trigger ledger offloading

**Expected behavior**

Ledger offloading should work with large ledger sizes

**Workaround**

```
# ensure that ledgers don't grow over 1500MB
managedLedgerMaxSizePerLedgerMbytes=1500
managedLedgerMinLedgerRolloverTimeMinutes=0
```
or
```
# increase block size to 128MB, maximum file size doubles to 4GB
gcsManagedLedgerOffloadMaxBlockSizeInBytes=134217728
```

**Additional context**

JClouds issue reported as [[JCLOUDS-1606] Cannot upload more than 32 parts to GCS](https://issues.apache.org/jira/browse/JCLOUDS-1606).

### PR DESCRIPTION
**Pull request by pgier**
Upgrade jclouds to fix offload issue.

Fixes #15159

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [ X ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/pgier/pulsar/pull/11

### CODE REVIEW

**Comment by pgier** [comment]
Hmm, I guess this PR was premature, 2.6.0 has only released an RC but not the final release yet.  I'll leave this open for when they do release 2.6.0.

**Review by dave2wave — COMMENTED** [review]
Here's the vote thread: https://lists.apache.org/thread/47zpc6sqjhmwwsrvtl1kz5mmjjxk12hm

It looks like once Andrew votes it will pass and the release will happen.

**Review by lhotari — APPROVED** [review]
LGTM

**Review by dao-jun — APPROVED** [review]

**Comment by lhotari** [comment]
@dao-jun it seems that there are failures after upgrading to 2.6.0 and closing and reopening to get the latest master changes won't make a difference.

**Comment by eolivelli** [comment]
It seems that there is some work to do, I am seeing these errors on CI:

```
BlobStoreBackedInputStreamTest.start
Unable to create injector, see the following errors:

1) [Guice/MissingImplementation]: No implementation for inject.Provider<Gson> was bound.

Did you mean?
    Gson bound at GsonModule.provideGson(GsonModule.java:103)
      \_ installed by: RestModule -> GsonModule

Requested by:
1  : GsonModule$PropertiesAdapter.<init>(GsonModule.java:260)
      \_ for 1st parameter
     at GsonModule.provideGson(GsonModule.java:103)
      \_ for 5th parameter
     at GsonModule.provideGson(GsonModule.java:103)
      \_ installed by: RestModule -> GsonModule
```

**Comment by lhotari** [comment]
@pgier do you have a chance to check the test failures and fix them? thanks

**Comment by dao-jun** [comment]
> Looks like jclouds upgrade requires a gson upgrade.

Please help resolve these failures,

**Comment by dao-jun** [comment]
image
image
seems we also need to update `guice` to 7.0.0

**Comment by dao-jun** [comment]
Since I upgraded guice to 7.0.0, seems still cannot fix these failures

**Comment by lhotari** [comment]
> Since I upgraded guice to 7.0.0, seems still cannot fix these failures

@dao-jun It should be possible to set the versions specificly to [`jclouds-shaded/pom.xml`](https://github.com/apache/pulsar/blob/master/jclouds-shaded/pom.xml), in a `dependencyManager` block so that the versions are only applied to jclouds-shaded within Pulsar.
Example of this approach: https://github.com/apache/pulsar/blob/37d88b8ff3e8cf9b7577a014c025a602bb75ff3b/pulsar-io/alluxio/pom.xml#L86-L108 .

**Comment by lhotari** [comment]
I pushed an attempt to set versions in jclouds-shaded/pom.xml

**Comment by lhotari** [comment]
@dao-jun  Looks like something is still missing:

```
  org.apache.pulsar.jcloud.shade.com.google.common.util.concurrent.ExecutionError: org.apache.pulsar.jcloud.shade.com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: jakarta/annotation/PostConstruct
  	at org.apache.pulsar.jcloud.shade.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2083) ~[?:?]
  	at org.apache.pulsar.jcloud.shade.com.google.common.cache.LocalCache.get(LocalCache.java:4011) ~[?:?]
  	at org.apache.pulsar.jcloud.shade.com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4034) ~[?:?]
  	at org.apache.pulsar.jcloud.shade.com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5010) ~[?:?]
  	at org.apache.pulsar.jcloud.shade.com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5017) ~[?:?]
  	at org.apache.pulsar.jcloud.shade.com.google.inject.internal.FailableCache.get(FailableCache.java:61) ~[?:?]
  	at org.apache.pulsar.jcloud.shade.com.google.inject.internal.ConstructorInjectorStore.get(Construct
```

**Comment by dao-jun** [comment]
I had tried to add more shaded pkgs, but seems not works

**Comment by lhotari** [comment]
> I had tried to add more shaded pkgs, but seems not works

@dao-jun I made more changes just a while ago.

**Comment by lhotari** [comment]
The tests pass now, but it might be useful to reduce the shaded dependencies to minimum when there aren't conflicts. I simply copy-pasted multiple deps from jclouds-project pom to see if it helps, and it did.

**Comment by lhotari** [comment]
@pgier @dave2wave  This has been merged to master branch. do you have a chance to run some tests with the changes to see if it really fixes the issues with >2GB on GCP?

**Comment by pgier** [comment]
@lhotari Thanks for fixing this.  We should be able to test it, but maybe not for a couple more weeks.

**Comment by lhotari** [comment]
> @lhotari Thanks for fixing this. We should be able to test it, but maybe not for a couple more weeks.

@pgier do you have any test results to share about JClouds 2.6.0 ? I'm thinking of cherry-picking to maintenance branches after there's more confirmation that JClouds 2.6.0 works well with Pulsar. /cc @dave2wave @eolivelli @nicoloboschi

**Comment by nikhil-ctds** [comment]
@lhotari With the above fix I tried testing GCS offloader with ledgers of size >= 2.5gb. I'm still facing the same error

```Error in offload
null

Reason: Error offloading: org.apache.bookkeeper.mledger.ManagedLedgerException: java.util.concurrent.CompletionException: org.jclouds.http.HttpResponseException: command: POST https://www.googleapis.com/storage/v1/b/bucket-cognitree-ls1258/o/d7f69abd-dc45-4fc1-bbe3-bd9daaa8fea7-ledger-9/compose HTTP/1.1 failed with response: HTTP/1.1 400 Bad Request; content: [{
  "error": {
    "code": 400,
    "message": "The number of source components provided (38) exceeds the maximum (32)",
    "errors": [
      {
        "message": "The number of source components provided (38) exceeds the maximum (32)",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
]
```

I have also written a simple code using Jclouds 2.6.0 to upload a large file of size 3gb to GCS bucket, it has uploaded successfully.

**Comment by lhotari** [comment]
> @lhotari With the above fix I tried testing GCS offloader with ledgers of size >= 2.5gb. I'm still facing the same error
> 
> ```
> Error in offload
> null
> 
> Reason: Error offloading: org.apache.bookkeeper.mledger.ManagedLedgerException: java.util.concurrent.CompletionException: org.jclouds.http.HttpResponseException: command: POST https://www.googleapis.com/storage/v1/b/bucket-cognitree-ls1258/o/d7f69abd-dc45-4fc1-bbe3-bd9daaa8fea7-ledger-9/compose HTTP/1.1 failed with response: HTTP/1.1 400 Bad Request; content: [{
>   "error": {
>     "code": 400,
>     "message": "The number of source components provided (38) exceeds the maximum (32)",
>     "errors": [
>       {
>         "message": "The number of source components provided (38) exceeds the maximum (32)",
>         "domain": "global",
>         "reason": "invalid"
>       }
>     ]
>   }
> }
> ]
> ```
> 
> I have also written a simple code using Jclouds 2.6.0 to upload a large file of size 3gb to GCS bucket, it has uploaded successfully.

@nikhil-ctds Do you have a chance to rerun the test with `gcsManagedLedgerOffloadMaxBlockSizeInBytes=134217728` ?
The default value `gcsManagedLedgerOffloadMaxBlockSizeInBytes=67108864` will limit the max upload size to 2048MiB (64MiB * 32). Doubling gcsManagedLedgerOffloadMaxBlockSizeInBytes to `134217728` should lift the limit to 4096MiB.
Can you please verify? Thanks

**Comment by lhotari** [comment]
@nikhil-ctds I created #22554 that changes the default value of `gcsManagedLedgerOffloadMaxBlockSizeInBytes`. It would be helpful if you could test that `gcsManagedLedgerOffloadMaxBlockSizeInBytes=134217728` fixes the issue. thanks
