### PR TITLE
Fixed static linking on C++ lib on MacOS

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Static linking of C++ client lib on MacOS (which is used in building the Python wheel file) got broken in #4071. Making sure we link statically with all the libs minus `libz` and `libcurl`.

### CODE REVIEW

**Comment by aahmed-se** [comment]
it's broken in jenkins
```
 CMakeFiles/Makefile2:351: recipe for target 'examples/CMakeFiles/SampleConsumerListener.dir/all' failed
make[1]: *** [examples/CMakeFiles/SampleConsumerListener.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 81%] Linking CXX shared library _pulsar.so
[ 81%] Linking CXX executable perfConsumer
[ 81%] Linking CXX executable perfProducer
../lib/libpulsar.so.2.5.0-SNAPSHOT: undefined reference to `google::protobuf::internal::WireFormatLite::WriteInt64(int, long, google::protobuf::io::CodedOutputStream*)'
../lib/libpulsar.so.2.5.0-SNAPSHOT: undefined reference to `vtable for google::protobuf::MessageLite'
../lib/libpulsar.so.2.5.0-SNAPSHOT: undefined reference to `google::protobuf::MessageLite::ParseFromArray(void const*, int)'
../lib/libpulsar.so.2.5.0-SNAPSHOT: undefined reference to `google::protobuf::io::CodedOutputStream::~CodedOutputStream()'
../lib/libpulsar.so.2.5.0-SNAPSHOT: undefined reference to `google::protobuf::internal::WireFormatLite::WriteDouble(int, double, google::protobuf::io::CodedOutputStream*)'
../lib/libpulsar.so.2.5.0-SNAPSHOT: undefined reference to `google::protobuf::internal::VerifyVersion(int, int, char const*)'
../lib/libpulsar.so.2.5.0-SNAPSHOT: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBool(int, bool, google::protobuf::io::CodedOutputStream*)'
../lib/libpulsar.so.2.5.0-SNAPSHOT: undefined reference to `google::protobuf::internal::WireFormatLite::WriteUInt32(int, unsigned int, google::protobuf::io::CodedOutputStream*)'
../lib/libpulsar.so.2.5.0-SNAPSHOT: undefined reference to 
````

**Comment by wolfstudy** [comment]
@merlimat  l will change the `Milestone` to 2.4.3. So we can cut 2.4.2 and if needed 
2.4.3 in a few weeks.

**Comment by aahmed-se** [comment]
we need to exclude the python lib from the static build /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python
```/usr/local/lib/python3.7/site-packages/_pulsar.cpython-37m-darwin.so:
	@rpath/_pulsar.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python (compatibility version 3.7.0, current version 3.7.0)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
```

**Comment by tuteng** [comment]
run java8 tests
run cpp tests

**Comment by aahmed-se** [comment]
run java8 tests
run cpp tests

**Comment by jiazhai** [comment]
run java8 tests
run integration tests

**Comment by tuteng** [comment]
retest this please

**Comment by tuteng** [comment]
run cpp tests
run java8 tests

**Comment by tuteng** [comment]
run cpp tests

**Comment by tuteng** [comment]
run cpp tests
