### PR TITLE
[cherry-pick] [branch-3.0] Fix getting last message ID when there are ongoing transactions

### PR DESCRIPTION
**Pull request by thetumbled**
### Motivation
Exception is found in branch 3.0:
https://github.com/apache/pulsar/pull/22024#issuecomment-1965921600

### Modifications

The root is that we do not cherry pick https://github.com/apache/pulsar/pull/21466 into branch 3.0, and the test code rely on this pr.
Moreover, the test code in https://github.com/apache/pulsar/pull/21466 is merged into branch 3.0 along with my pr https://github.com/apache/pulsar/pull/22024, so we do not need to cherry pick those test code in this pr.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is already covered by existing tests, such as *(please describe tests)*.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/thetumbled/pulsar/pull/43

### CODE REVIEW

**Comment by thetumbled** [comment]
PTAL, thanks.
@lhotari @Technoboy-

**Review by Technoboy- — APPROVED** [review]

**Comment by lhotari** [comment]
@Technoboy- I think we should cherry-pick #21466 first , that will ease tracking in the future

**Review by lhotari — CHANGES_REQUESTED** [review]
let's first cherry-pick #21466

**Comment by thetumbled** [comment]
> let's first cherry-pick #21466

may be change the title is enough?

**Comment by Technoboy-** [comment]
> @Technoboy- I think we should cherry-pick #21466 first , that will ease tracking in the future

Can't cherry-pick directly. Using this and comment on the #21466 is enough

**Comment by lhotari** [comment]
Closing and reopening as an attempt to trigger the CI builds to run. For some reason, the build didn't get triggered.

**Comment by thetumbled** [comment]
Some test do not pass:
`mvn -B -T 1C -ntp -Pcore-modules,-main clean install -DskipTests -Dlicense.skip=true -Drat.skip=true -Dcheckstyle.skip=true`
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java
image
TimeUnitToSecondsConverter.class is introduced by https://github.com/apache/pulsar/pull/20782, but we do not cherry pick it into branch 3.0. 
However, https://github.com/apache/pulsar/pull/22101 is cherry picked into branch-3.0, which rely on TimeUnitToSecondsConverter.class.

So the solution is: first, cherry pick https://github.com/apache/pulsar/pull/20782 into branch-3.0, then we use this pr https://github.com/apache/pulsar/pull/22143 to fix the problem.

**Comment by thetumbled** [comment]
> Some test do not pass: `mvn -B -T 1C -ntp -Pcore-modules,-main clean install -DskipTests -Dlicense.skip=true -Drat.skip=true -Dcheckstyle.skip=true`
> 
> ```
> cannot find symbol
> Error:    symbol:   class TimeUnitToSecondsConverter
> Error:    location: class org.apache.pulsar.admin.cli.CmdNamespaces.SetOffloadThreshold
> ```
> 
> image
> TimeUnitToSecondsConverter.class is introduced by #20782 , but we do not cherry pick it into branch 3.0. However, #22101 is cherry picked into branch-3.0, which rely on TimeUnitToSecondsConverter.class.
> 
> So the solution is: first, cherry pick #20782 into branch-3.0, then we use this pr #22143 to fix the problem. PTAL, thanks. @lhotari @Technoboy-

The problem has been fixed by https://github.com/apache/pulsar/pull/22169, we can proceed with reviewing this pr. @lhotari @heesung-sn

**Review by heesung-sn — APPROVED** [review]

**Comment by heesung-sn** [comment]
I don't see this change in this cherry-pick PR. 

https://github.com/apache/pulsar/pull/21466/files#diff-ecd728301a585f256e8a649b5e65b28c166194477355b3a1eefc198d014c25d3R450

@thetumbled can you check again?

**Comment by thetumbled** [comment]
> I don't see this change in this cherry-pick PR.
> 
> https://github.com/apache/pulsar/pull/21466/files#diff-ecd728301a585f256e8a649b5e65b28c166194477355b3a1eefc198d014c25d3R450
> 
> @thetumbled can you check again?

We have cherry pick pr 

> I don't see this change in this cherry-pick PR.
> 
> https://github.com/apache/pulsar/pull/21466/files#diff-ecd728301a585f256e8a649b5e65b28c166194477355b3a1eefc198d014c25d3R450
> 
> @thetumbled can you check again?

Sorry for missing it. PTAL, thanks.

**Comment by lhotari** [comment]
Thank you @thetumbled for this PR. I ended up using your merge conflict resolution into this commit: 4489d03f .
I hope we find a way to fix our process that we don't end up in this problems that often in the future. I have started a discussion thread on the dev mailing list: https://lists.apache.org/thread/j6qvt45rndnvjypcmqxsfmddqt41bxjv
