### PR TITLE
[schema] Fix joda dependency issue.

### LINKED ISSUE #4179: [schema] java.lang.NoClassDefFoundError: org/joda/time/ReadablePartial
**Describe the bug**

When using AvroSchema from latest master, it throws following exceptions:

```
java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/joda/time/ReadablePartial

	at org.apache.pulsar.client.internal.ReflectionUtils.catchExceptions(ReflectionUtils.java:36)
	at org.apache.pulsar.client.internal.DefaultImplementation.newAvroSchema(DefaultImplementation.java:212)
	at org.apache.pulsar.client.api.Schema.AVRO(Schema.java:196)
	at io.streamnative.tests.pulsar.schema.CreateDifferentSchemaAfterDeleteSchemaTest.testCreateSchemaAfterDeletion(CreateDifferentSchemaAfterDeleteSchemaTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at io.streamnative.tests.common.framework.SystemTestRunner.invokeTest(SystemTestRunner.java:219)
	at io.streamnative.tests.common.framework.SystemTestRunner.runChild(SystemTestRunner.java:212)
	at io.streamnative.tests.common.framework.SystemTestRunner.runChild(SystemTestRunner.java:52)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NoClassDefFoundError: org/joda/time/ReadablePartial
	at org.apache.pulsar.client.impl.schema.AvroSchema.<clinit>(AvroSchema.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.pulsar.client.internal.DefaultImplementation.lambda$newAvroSchema$24(DefaultImplementation.java:214)
	at org.apache.pulsar.client.internal.ReflectionUtils.catchExceptions(ReflectionUtils.java:34)
	... 30 more
Caused by: java.lang.ClassNotFoundException: org.joda.time.ReadablePartial
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
```

**To Reproduce**

1. Build the latest master.
2. Use the AvroSchema from latest master. It will throws the above exception.

**Expected behavior**

No exception should be thrown.

**Additional context**

I think the problem introduced by #3900. It doesn't shade the joda library properly.

### PR DESCRIPTION
**Pull request by codelipenghui**
Fixes #4179 

### Modifications

Change joda-time dependency scope.
Add integration test for avro logical types.

### Verifying this change

This change added tests and can be verified by integration test

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The public API: (yes)
  - The schema: (yes)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by sijie** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by sijie** [comment]
@codelipenghui 

I think you need to fix binary license.

```
+ src/check-binary-license ./distribution/server/target/apache-pulsar-2.4.0-SNAPSHOT-bin.tar.gz
joda-time-joda-time-2.10.1.jar unaccounted for in LICENSE
joda-time-joda-time-2.9.3.jar mentioned in LICENSE, but not bundled
joda-time-2.10.1.jar unaccounted for in lib/presto/LICENSE
```

File: pulsar-client/pom.xml [hunk 1]
```diff
@@ -116,6 +116,11 @@
       <groupId>com.fasterxml.jackson.module</groupId>
       <artifactId>jackson-module-jsonSchema</artifactId>
     </dependency>
+
+    <dependency>
+      <groupId>joda-time</groupId>
+      <artifactId>joda-time</artifactId>
```
Comment (merlimat) [inline pulsar-client/pom.xml]: Should we also include in the shaded jar

Comment (codelipenghui) [reply pulsar-client/pom.xml]: joda-time lib is used by logical types in pulsar avro schema. Considering logical types is user-facing types, so not included in the shaded jar.

Comment (merlimat) [reply pulsar-client/pom.xml]: Makes sense. Would it be possible to have it as an optional dependency then? In the same way as is Protobuf for pulsar-client? 

For Protobuf, the reason is that if application uses Protobuf they will already have that in their classpath. Same for Joda, if application wants to get the schema of Joda date, they'll already have that.

If we make it optional, it would have less chances to conflict with other versions in the application classpath.

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by codelipenghui** [comment]
run java8 tests
run integration tests

**Comment by sijie** [comment]
run integration tests
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests
run integration tests

File: pulsar-client/pom.xml (hunk 1 above)
Comment (codelipenghui) [reply pulsar-client/pom.xml]: I'm already make it optional.

**Comment by codelipenghui** [comment]
run integration tests

**Comment by merlimat** [comment]
run java8 tests

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AvroSchema.java [hunk 2]
```diff
@@ -44,27 +44,32 @@
...
+            reflectDataNotAllowNull.addLogicalTypeConversion(new TimeConversions.DateConversion());
+            reflectDataNotAllowNull.addLogicalTypeConversion(new TimeConversions.TimestampConversion());
+            reflectDataNotAllowNull.addLogicalTypeConversion(new TimeConversions.LossyTimeMicrosConversion());
+            reflectDataNotAllowNull.addLogicalTypeConversion(new TimeConversions.LossyTimestampMicrosConversion());
+            reflectDataNotAllowNull.addLogicalTypeConversion(new TimeConversions.TimeMicrosConversion());
+            reflectDataNotAllowNull.addLogicalTypeConversion(new TimeConversions.TimestampMicrosConversion());
+            reflectDataNotAllowNull.addLogicalTypeConversion(new TimeConversions.TimeConversion());
+        } catch (Throwable t) {
+            LOG.warn("Avro logical types are not available. If you are going to use avro logical types, " +
+                    "you can include `joda-time` in your dependency.");
```
Comment (merlimat) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AvroSchema.java]: @codelipenghui One last ask. I missed this one. Can we have this message as debug instead of warn? Otherwise it would print the warning for everyone, even if not interested in using Joda-Time types with Avro.

Comment (codelipenghui) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AvroSchema.java]: Makes sense.

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by sijie** [comment]
run cpp tests
run java tests

**Comment by sijie** [comment]
run java8 tests
