### PR TITLE
Fix: typo and compilation error

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation
Right now, pulsar build is failing due to typo introduced in #7078 . Fixed the typo.

### CODE REVIEW

**Comment by merlimat** [comment]
@rdhabalia I've submitted the same fix this morning: #7144
