### PR TITLE
[pip][design] PIP-281: Add notifyError method on PushSource

### PR DESCRIPTION
**Pull request by shibd**
### Motivation

Refer to `pip-281.md`

BTW: This is a very simple change and is forward compatible. Sorry, I didn't notice that this change requires PIP before, so the related PRs have been merged.
- https://github.com/apache/pulsar/pull/20791

If this PIP vote does not pass, I revert this PR after that.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

File: pip/pip-281.md [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+}
+```
+
+Just like the implementation of the current [BatchPushSource](https://github.com/apache/pulsar/blob/branch-3.0/pulsar-io/core/src/main/java/org/apache/pulsar/io/core/BatchPushSource.java)
+
+
+BTW: This is a very simple change and is forward compatible. Sorry, I didn't notice that this change requires PIP before, so the related PRs have been merged.
+- https://github.com/apache/pulsar/pull/20791
+
+If this PIP vote does not pass, I revert this PR after that.
```
Comment (RobertIndie) [inline pip/pip-281.md:45]: I think we could remove these line:
> Sorry, I didn't notice that this change requires PIP before, so the related PRs have been merged.
> - https://github.com/apache/pulsar/pull/20791
> If this PIP vote does not pass, I revert this PR after that.

It's not much relevant to this PIP.

File: pip/pip-281.md [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+
+
+### Compatibility
+
+This PIP is to provide a method for users to use, not an new interface.
```
Comment (RobertIndie) [inline pip/pip-281.md:50]: I think the `new interface` here is referred to the Java interface? But adding a new method to a class is actually adding a new interface method(although it's not a Java interface class). Right?

File: pip/pip-281.md (hunk 1 above)
Comment (shibd) [reply pip/pip-281.md:45]: Agree, just comment on this PR.

File: pip/pip-281.md (hunk 2 above)
Comment (shibd) [reply pip/pip-281.md:50]: > I think the new interface here is referred to the Java interface?

Yes, I mean, not a new interface method, so don't have to force the user to implement it. So it is forward compatible

Comment (RobertIndie) [reply pip/pip-281.md:50]: Thanks. I get your point

**Review by RobertIndie — APPROVED** [review]

**Comment by BewareMyPower** [comment]
@Anonymitaet Could you help review from a perspective of technical writer?

File: pip/pip-281.md [hunk 3]
```diff
@@ -0,0 +1,103 @@
+# Title: [io] Add notifyError method on PushSource
+
+## Motivation
+
+In function framework, when [source.read()](https://github.com/apache/pulsar/blob/f7c0b3c49c9ad8c28d0b00aa30d727850eb8bc04/pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java#L496-L506) method throw exception, it will trigger close function instance. If it is in the k8s environment, it will be restarted
```
Comment (Anonymitaet) [inline pip/pip-281.md:5]:
```suggestion
In function framework, when [source.read()](https://github.com/apache/pulsar/blob/f7c0b3c49c9ad8c28d0b00aa30d727850eb8bc04/pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java#L496-L506) method throws an exception, it will trigger close function instance. If it is in the k8s environment, it will be restarted
```

File: pip/pip-281.md [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+
+On io source connector, we provide [PushSource](https://github.com/apache/pulsar/blob/branch-3.0/pulsar-io/core/src/main/java/org/apache/pulsar/io/core/PushSource.java) class for users to use, and users can extend this class to quickly implement the push message model.
```
Comment (Anonymitaet) [inline pip/pip-281.md:7]:
```suggestion
on IO source connector, you can use the [PushSource](https://github.com/apache/pulsar/blob/branch-3.0/pulsar-io/core/src/main/java/org/apache/pulsar/io/core/PushSource.java) class and extend it to quickly implement the push message model.
```

File: pip/pip-281.md [hunk 5]
```diff
@@ -0,0 +1,103 @@
...
+It overrides the `read` method and provides the `consume` method for the user to call.
+
+However, if the source connector that extends from the class,
```
Comment (Anonymitaet) [inline pip/pip-281.md:10]:
```suggestion
However, if the source connector extends from the class, 
```

File: pip/pip-281.md [hunk 6]
```diff
@@ -0,0 +1,103 @@
...
+It overrides the `read` method and provides the `consume` method for the user to call.
+
+However, if the source connector that extends from the class, 
+it cannot notify the function framework if it encounters an exception while consuming data internally, 
+in other words, the function call `source.read()` never triggers an exception and never exits the process.
+
+
+## Goals
+
+Add `notifyError` method on PushSource, This method can receive an exception and put the exception in the queue. The next time an exception is `read`, will throws it.
```
Comment (Anonymitaet) [inline pip/pip-281.md:17]:
```suggestion
Add the `notifyError` method on PushSource. This method can receive an exception and put the exception in the queue. The next time an exception is `read`, it will throw it.
```

throw "it", throw what?

File: pip/pip-281.md [hunk 7]
```diff
@@ -0,0 +1,103 @@
...
+  }
+}
+```
+
+Just like the implementation of the current [BatchPushSource](https://github.com/apache/pulsar/blob/branch-3.0/pulsar-io/core/src/main/java/org/apache/pulsar/io/core/BatchPushSource.java)
+
+
+### Compatibility
+
+This PIP is to provide a method for users to use, not an new interface.
```
Comment (Anonymitaet) [inline pip/pip-281.md:44]:
```suggestion
This PIP is to provide a method for users rather than introducing a new interface. 
```

File: pip/pip-281.md [hunk 8]
```diff
@@ -0,0 +1,103 @@
...
+Just like the implementation of the current [BatchPushSource](https://github.com/apache/pulsar/blob/branch-3.0/pulsar-io/core/src/main/java/org/apache/pulsar/io/core/BatchPushSource.java)
+
+
+### Compatibility
+
+This PIP is to provide a method for users to use, not an new interface. 
+
+- So it is forward compatible
+- However, connector using this method are not backward compatible.
+For example, the Kafka source connector compiles with version 3.1(include this pip) Pulsar dependencies and uses the `notifyError` method, and if it switches back to version 3.0(exclude this pip) Pulsar compilation, it will encounter compilation errors.
```
Comment (Anonymitaet) [inline pip/pip-281.md:48]: This is a long sentence with unclear clauses. What do you intend to mean?

File: pip/pip-281.md [hunk 9]
```diff
@@ -0,0 +1,103 @@
...
+
+### In Scope
+
+Use this method, Like all current source connectors that extends the PushSource, process exit can be implemented. Such as:
```
Comment (Anonymitaet) [inline pip/pip-281.md:52]: This sentence is unclear. What do you intend to mean?

File: pip/pip-281.md (hunk 8 above)
Comment (shibd) [reply pip/pip-281.md]: I refactor this sentence, PTAL.

File: pip/pip-281.md (hunk 9 above)
Comment (shibd) [reply pip/pip-281.md]: I refactor this sentence, PTAL.

File: pip/pip-281.md (hunk 8 above)
Comment (Anonymitaet) [reply pip/pip-281.md]: Sorry, it's still unclear. What's the relationship between "the Kafka source connector compiles with version 3.1(include this pip) Pulsar dependencies and uses the `notifyError` method," and the latter sentence?

File: pip/pip-281.md [hunk 10]
```diff
@@ -0,0 +1,103 @@
...
+
+
+### Compatibility
+
+This PIP is to provide a method for users rather than introducing a new interface.
+
+- So it is forward compatible
+- However, connector using this method are not backward compatible.
+For example, the currently Kafka source connector compiles with version 3.1(include this pip) Pulsar dependencies and uses the `notifyError` method, 
+if it switches back to version 3.0(exclude this pip) Pulsar to compile, it will encounter compile errors.
```
Comment (Anonymitaet) [inline pip/pip-281.md:48]: 1. What's the meaning of "(include this pip)"?
2. Does the Kafka source connector "use" a method?
3. "Who" switches back to 3.0? Do you mean Kafka source connector complies with Pulsar  3.0?

File: pip/pip-281.md [hunk 11]
```diff
@@ -0,0 +1,103 @@
...
+
+### In Scope
+
+Use this method, current source connectors can extends the `PushSource`, and use `notifyError` method to throw exception. Such as:
```
Comment (Anonymitaet) [inline pip/pip-281.md:52]: "Use this method", what does "this" refer to? Need to show it explicitly

File: pip/pip-281.md (hunk 10 above)
Comment (shibd) [reply pip/pip-281.md]: > What's the meaning of "(include this pip)"?

That means the 3.1 version has this pip-related feature.

> Does the Kafka source connector "use" a method?

This is an example, in fact it is not currently used, and then this PIP will be PR to fix it

> "Who" switches back to 3.0? Do you mean the Kafka source connector complies with Pulsar 3.0?
Kafka source connector. No, I'm giving examples of incompatible scenarios.


hi @Anonymitaet Please help take another look at the latest sentence, thanks.

File: pip/pip-281.md [hunk 12]
```diff
@@ -43,13 +43,13 @@ Just like the implementation of the current [BatchPushSource](https://github.com
 This PIP is to provide a method for users rather than introducing a new interface.
 
 - So it is forward compatible
-- However, connector using this method are not backward compatible.
-For example, the currently Kafka source connector compiles with version 3.1(include this pip) Pulsar dependencies and uses the `notifyError` method, 
-if it switches back to version 3.0(exclude this pip) Pulsar to compile, it will encounter compile errors.
+- However, connector using this method are not backward compatible. 
+For example, If `Kafka source` connector depends on version v3.0(include this pip feature) of pulsar-io and uses the `notifyError` method, 
+when it switches back to depends on 3.0(not include this pip feature) version of pulsar-io to compile will encounter compile errors.
```
Comment (Anonymitaet) [inline pip/pip-281.md:48]:
```suggestion
- However, connectors using this method are not backward compatible. 
For example, If a Kafka source connector built upon pulsar-io v3.1 (including features introduced in this PIP) and uses the `notifyError` method, 
when it switches back to pulsar-io v3.0 (excluding features introduced in this PIP), it will encounter errors during compilation. 
```

do you intend to mean this?

**Review by Anonymitaet — APPROVED** [review]
