### ISSUE TITLE
[Bug] [Regression] etcd mTLS doesn't work on 3.3.1

### ISSUE THREAD

**Issue by martin31821** [apache/pulsar#23160]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

3.3.1 - server only, running on Amazon Linux 2

### Minimal reproduce step

- Setup etcd cluster with mTLS auth enabled 
- Setup pulsar-broker with etcd configured for mTLS

example configuration:
```
# broker.conf:
metadataStoreConfigPath: /pulsar/metadata-config/etcd.yaml
metadataStoreUrl: "etcd:https://pulsar-etcd-headless:2379"
configurationMetadataStoreUrl: "etcd:https://pulsar-etcd-headless:2379"

# /pulsar/metadata-config/etcd.yaml
useTls: true
tlsProvider: "OPENSSL"
tlsTrustCertsFilePath: "/pulsar/etcd-cert/ca.crt"
tlsKeyFilePath: "/pulsar/etcd-cert/tls.key"
tlsCertificateFilePath: "/pulsar/etcd-cert/tls.crt"
authority: ""
```

### What did you expect to see?

Working mTLS connection to etcd.

### What did you see instead?

java.lang.NoSuchMethodError because of this PR: https://github.com/apache/pulsar/pull/22892 
The mentioned PR is the last time, when jetcd has been touched.

### Anything else?

It works fine on v3.3.0 with the above config. I'm willing to submit a PR, but I don't know how to fix it :|

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lhotari** [comment]
> java.lang.NoSuchMethodError because of this PR: https://github.com/apache/pulsar/pull/22892

@martin31821  Please share the full exception stack trace.

**Comment by lhotari** [comment]
#23513 is related.
