### ISSUE TITLE
[Bug] NoClassDefFoundError: org/apache/pulsar/client/api/PulsarClientException$FeatureNotSupportedException in pulsar client v3.0.7

### ISSUE THREAD

**Issue by alpreu** [apache/pulsar#23404]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

Broker version: 3.0.7 (same issue with broker version 3.0.6)
**Client version: 3.0.7**

### Minimal reproduce step

# gradle.build
```
 implementation group: 'org.apache.pulsar', name: 'pulsar-client-all', version: 3.0.7
 ```
 
 # Java class
```
class Scratch {
    public static void main(String[] args) {
        try {
            ClientBuilder clientBuilder = PulsarClient.builder();
            clientBuilder.serviceUrl("pulsar://localhost:6650");
            // stepping through with a debugger, at this step it fails
            PulsarClient client = clientBuilder.build();
            // this is not reached
            Consumer<byte[]> consumer = client.newConsumer().topic("public/default/xyz").subscriptionName("scratch").subscribe();
            consumer.receive();
        } catch (PulsarClientException e) {
            throw new RuntimeException(e);
        }
    }
```

### What did you expect to see?

Client should be successfully created and consumer started. This works with client version 3.0.6 but not on the 3.0.7

### What did you see instead?

Client is not created successfully. See Stacktrace below:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/pulsar/client/api/PulsarClientException$FeatureNotSupportedException
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:214)
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:160)
	at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:63)
	at com.streamvisor.example.Scratch.main(scratch_1.java:16)
Caused by: java.lang.ClassNotFoundException: org.apache.pulsar.client.api.PulsarClientException$FeatureNotSupportedException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 4 more
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment]
the reported issue cannot be reproduced, I checked with https://github.com/lhotari/pulsar-issue-23404 and that works fine.
build.gradle is at https://github.com/lhotari/pulsar-issue-23404/blob/master/app/build.gradle .
I also added an example of configuring Log4j2 so that log output can be used to detected issues instead of the need to use a debugger.

**Comment by lhotari** [comment]
There have been issues in the past where mixing multiple Pulsar versions have caused issues. The pulsar-bom has been a solution, however that's only available since 3.2.0 version of Pulsar .
Does 3.3.2 work? How about with pulsar-bom?
https://pulsar.apache.org/docs/3.3.x/client-libraries-java-setup/#pulsar-bom

You can use Gradle build scans or gradle's `dependencies` task to debug dependency issues. Since most likely you have conflicting dependencies in your application.

Without pulsar-bom, you can use Gradle's features to address this. 

```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'org.apache.pulsar') {
            details.useVersion '3.0.7' // specify the version you want to enforce
        }
    }
}
```

@alpreu Does your problem reproduce if you add that to your build.gradle file?

**Comment by alpreu** [comment]
After looking into it the root cause was Spring Boot (`spring-boot-dependencies` POM to be exact) bringing in another version of the pulsar libraries.

Specifying a resolution strategy in the gradle build file as shown by @lhotari fixed the issue.

**Comment by lhotari** [comment]
The Pulsar docs have been updated to show how the Pulsar version must be set when using Spring Boot default Gradle build with Spring Dependencies Management plugin: https://pulsar.apache.org/docs/4.0.x/client-libraries-java-setup/#gradle-with-spring-boot-using-spring-dependency-management-plugin
