### ISSUE TITLE
[Bug] pulsar-client-v5 + pulsar-client-admin on the same classpath: Duplicate incompatible ClientCnx (shaded vs unshaded Netty)

### ISSUE THREAD

**Issue by pdolif** [apache/pulsar#26502]
### Search before reporting

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [x] I understand that [unsupported versions](https://pulsar.apache.org/contribute/release-policy/#supported-versions) don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### User environment

- Client library type: Java
- Client library version: 5.0.0-M1 (`pulsar-client-v5` + `pulsar-client-admin`)
- Not present with the same combination of 4.2.4 `pulsar-client` + `pulsar-client-admin`

### Issue Description

A Java project that depends on both `pulsar-client-v5:5.0.0-M1` and `pulsar-client-admin:5.0.0-M1` ends up with two different, incompatible versions of `ClientCnx` on the classpath, causing a `NoSuchMethodError` at runtime. This combination, using both the Pulsar client and the admin client in the same project, worked fine on 4.2.4.

### Error messages

```text
java.lang.NoSuchMethodError: 'io.netty.channel.ChannelHandlerContext org.apache.pulsar.client.impl.ClientCnx.ctx()'
```

### Reproducing the issue

1. Create a Java project with these two dependencies:
   - `org.apache.pulsar:pulsar-client-v5:5.0.0-M1`
   - `org.apache.pulsar:pulsar-client-admin:5.0.0-M1`
2. Use both a v5 `PulsarClient` and a `PulsarAdmin` client in the same application/classpath.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by merlimat** [comment]
@pdolif Thanks for reporting this. I think the problem is that `pulsar-client-v5` is not shaded, though `pulsar-client-admin` is shaded by default. 

The proper solution would be to publish a `pulsar-client-v5` with shaded qualifier. 

An interim solution is to use `pulsar-client-admin-original` in the meantime.

**Comment by lhotari** [comment]
I'm working on a fix for this one since it could cause problems with many users.

**Comment by lhotari** [comment]
Two related PRs are open:

- #26544 fixes this issue by isolating the bundled Pulsar implementations in the shaded artifacts, including the incompatible `ClientCnx` classes and Netty checksum adapters. It keeps `pulsar-client-v5` intentionally unshaded and adds integration coverage for both classpath orders.
- #26545 adds two combined client/admin dependencies: **`pulsar-client-v5-all` for unshaded use** and **`pulsar-client-v5-shaded` for shaded use**. Once available, v5 applications needing the admin API should use one of these. Both include the **v4 client**, so v4 applications can migrate their dependency before migrating source code to v5.

The unshaded aggregate brings in the client/admin implementations transitively. The shaded artifact bundles the v4/v5 clients, admin implementation, and relocated third-party dependencies in one jar. Pulsar API modules and intentionally non-bundled libraries remain external.

**Why a separate shaded artifact rather than a classifier?** [Maven classifiers share the main artifact's POM and dependency list](https://maven.apache.org/pom.html). Selecting a shaded classifier still pulls in the unshaded implementations and their transitive dependencies. `pulsar-client-v5-shaded` has its own dependency-reduced POM, so both Maven and Gradle users can use one ordinary dependency declaration without a classifier or implementation exclusions on that dependency.

V5 applications should **not use `pulsar-client` or `pulsar-client-admin`**, either directly or transitively. Remove direct declarations and exclude these artifacts from dependencies that bring them in, so the classpath does not contain unnecessary duplicate shaded implementations and libraries. Use `pulsar-client-v5` for the unshaded client alone, or choose `pulsar-client-v5-all` / `pulsar-client-v5-shaded` for the combined client/admin dependency.

Detailed explanation: https://github.com/apache/pulsar/blob/lh/feat-client-v5-all/pulsar-client-v5-all/README.md
