### ISSUE TITLE
[Bug] Few commits are breaking the build on branch-3.1

### ISSUE THREAD

**Issue by mukesh-ctds** [apache/pulsar#22171]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

branch-3.1

### Minimal reproduce step

- Update the branch-3.1 with local code changes.
- Run `mvn install`

### What did you expect to see?

The build should compile.

### What did you see instead?

There are two compilation issue on the branch-3.1

1. 1st compilation issue is due to [6e8ad696141f28c37c6fc0086cf8d797cdb64ebc](https://github.com/apache/pulsar/commit/6e8ad696141f28c37c6fc0086cf8d797cdb64ebc)
    Here, the import statement is missing for lombok.Cleanup.
```
    [ERROR] COMPILATION ERROR : 
    [INFO] -------------------------------------------------------------
    [ERROR] /Documents/projects/pulsar/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java:[446,10] cannot find symbol
      symbol:   class Cleanup
      location: class org.apache.pulsar.broker.service.SystemTopicBasedTopicPoliciesServiceTest
```
2. 2nd compilation issue is due to [1fe385396a96c04ba8c18414024c95f1a251c27e](https://github.com/apache/pulsar/commit/1fe385396a96c04ba8c18414024c95f1a251c27e)
   This commit is not meant for `branch-3.1` as the pulsar-cli-utils module is not there on `branch-3.1`, it only there on `branch-3.2` & `master`. And the this commit is using `TimeUnitToSecondsConverter.class` which is from `pulsar-cli-utils`
```
    [ERROR] COMPILATION ERROR : 
    [INFO] -------------------------------------------------------------
    [ERROR] /Documents/projects/pulsar/pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java:[1986,25] cannot find symbol
    symbol:   class TimeUnitToSecondsConverter
    location: class org.apache.pulsar.admin.cli.CmdNamespaces.SetOffloadThreshold
    [INFO] 1 error
```
    

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lhotari** [comment]
@mukesh-ctds Yes, this is the case and it is being taken care of. Please check Pulsar Slack's #dev channel for more details and updates on this. https://apache-pulsar.slack.com/archives/C5ZSVEN4E/p1709293465986789
(to join slack, see https://pulsar.apache.org/community/#section-discussions to get the invite)
I'll also send an update to the dev mailing list.

**Comment by lhotari** [comment]
This has been resolved. branch-3.1 compiles. There's a manual build job running at https://github.com/apache/pulsar/actions/runs/8147294393
